apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: adservice-init
  files:
  - init.sh
  options:
    disableNameSuffixHash: true

components:
- ../../../common/env-configmaps
- ../../../common/health-check
- ../../../common/update-strategy

resources:
- adservice-deploy.yaml
- adservice-sa.yaml
- adservice-svc.yaml
- adservice-route.yaml
