apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox-container
  template:
    metadata:
      labels:
        app: toolbox-container
    spec:
      containers:
      - image: quay.io/noseka1/toolbox-container:basic
        imagePullPolicy: Always
        name: toolbox-container
      serviceAccountName: toolbox-container
