appName: app1
userGivenName: app1
destNamespace: app1
destServer: rosa-wus2-lab
srcPath: apps/app1/overlays/rosa-wus2-lab
srcRepoURL: https://github.com/noseka1/gitops-example-apps
srcTargetRevision: ""
labels: null
