apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: toolbox-container
  newName: quay.io/noseka1/toolbox-container
  newTag: basic

configMapGenerator:
- name: toolbox-container-init
  files:
  - init.sh

resources:
- toolbox-container-deploy.yaml
- toolbox-container-sa.yaml
- toolbox-container-svc.yaml
- toolbox-container-route.yaml
