apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: cartservice-init
  files:
  - init.sh
  options:
    disableNameSuffixHash: true

components:
- ../../../common/env-configmaps
- ../../../common/health-check
- ../../../common/update-strategy

resources:
- cartservice-deploy.yaml
- cartservice-sa.yaml
- cartservice-svc.yaml
- cartservice-route.yaml
