apiVersion: v1
kind: ConfigMap
metadata:
  name: database-env
data:
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.SQLServer2012Dialect
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.SQLServer2012Dialect
