apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-used
spec:
  template:
    spec:
      containers:
      - name: app
        readinessProbe:
          httpGet:
            port: 8080
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 8080
          periodSeconds: 10
